### ISSUE TITLE
Deploy only if changes to the path

### ISSUE THREAD

**Issue by morrislaptop** [digitalocean/sample-monorepo#5]
Is there a way to only deploy a particular component if there are changes within a certain path? Example structure:

```
- web
- common
- api
- marketing
```

If I push a change to `marketing`, then `marketing` would only deploy.

If I push a change inside `api`, then `api` would only deploy.

If I push a change inside `common`, then `web` and `api` would deploy.

Similar to GitHub actions and the `paths` property

**Comment by kamaln7** [comment]
👋🏼 @morrislaptop 

Thanks, this is a great suggestion! This is not supported at this time but I've added it to the list of feature requests. We've also received a request for the ability to manually deploy a specific component only, which might also be helpful, although it is not yet supported either.

I'm closing this issue for now as there is no ETA but let me know if you have any other thoughts!

**Comment by morrislaptop** [comment]
Ah ok triggering an individual component would be fine as i could do that from GitHub actions quite easily. Cheers
